### ISSUE TITLE
Prefix options are passed to pipe rather than prefix.

### ISSUE THREAD

**Issue by m59peacemaker** [goodbomb/angular-gulp-browserify-starter#10]
I believe this:

    .pipe(prefix("last 1 version", "> 1%", "ie 8", "ie 7"), {map: true})

ought to be this:

    .pipe(prefix("last 1 version", "> 1%", "ie 8", "ie 7", {map: true}))

The options object is being passed to `.pipe` as the second argument rather than to `prefix`.

**Comment by goodbomb** [comment]
I believe you are correct. I'm updating the project now. Thanks for the tip!
