### ISSUE TITLE
nested views/modules

### ISSUE THREAD

**Issue by BollingerInternational** [goodbomb/angular-gulp-browserify-starter#12]
Can you please give a clear example of submodules. Specifically what the moduleConfig.js file is supposed to look like? A working example? Currently, I have routes defined in appConfig.js, and I have a modules module that injects those modules defined in appConfig.js. Your file structure defines a module 3 that contains submodules, but you have no examples or explanations on how to get it working. Thank you.

**Comment by goodbomb** [comment]
Hi, I am pretty busy right now, but I'll try to introduce a working example this weekend.

**Comment by BollingerInternational** [comment]
Ben,

Thank you, I appreciate it.

Sincerely,

*August Bollinger*
Founder/Creator/Quant - Chayton Falke Global Equity™
Founder/Lead Data Scientist - Composite Analytics™
(949) 257-2854

Life can be absolutely phenomenal. And it should be. And it WILL be! :)

**Comment by goodbomb** [comment]
https://github.com/goodbomb/angular-gulp-browserify-starter/tree/develop

There you go. Have a look and let me know if you have any questions. Should be relatively straight forward.

Cheers!

**Comment by BollingerInternational** [comment]
Ben,
Thank you for all that work. It's a valid addition. However, I am seeing that getting to the about page requires my url to be localhost:5000/about. I apologize for not being clear, but what I understand as a nested view in ui-router, would be to have a pages module, and a nested view called about that would have the url localhost:5000/pages/about, and in the appConfig file perhaps a name like pages.about for the module? I apologize for being confused. Could you either debunk my thinking, or perhaps explain how nested views live in your framework? I realize you are quite busy, but this would do wonders for my progress. Thank you.

**Comment by goodbomb** [comment]
Sounds like you're more confused with Angular UI Router at this point. The URL that points to the module can be anything you want. So if you look at the ```pagesConfig.js``` file you'll notice there's a "url" field. That can literally be whatever you want it to be. So it can be ```pages/about``` if you want it to.

https://github.com/goodbomb/angular-gulp-browserify-starter/blob/develop/app/modules/pages/pagesConfig.js

That being said, if you want the pages module to be included as an abstract parent to the about module, all you'd have to do is something like this:

```
var pages = {
        name: 'pages',
        abstract: true,
        url: '/pages',
        template: '<div ui-view></div>',
        controller: 'PagesCtrl'
    },
    about = {
        name: 'pages.about',
        url: '/about',
        template: '<div about-view></div>',
        data: {
            moduleClasses: 'page',
            pageClasses: 'about',
            pageTitle: 'About',
            pageDescription: 'Some description.'
        }
    };

$stateProvider.state(pages);
$stateProvider.state(about);
```

I haven't tested it, so there may be some tweaking required, but you literally don't do anything different with the routing in this architecture than you would with any other angular app. The only difference is that your routes are segmented out into their respective modules instead of all of them being listed out in a single config file.

Does that make sense?

**Comment by BollingerInternational** [comment]
​Ben,

Yes it does. Thank you for the help. One last question...if I want unique
meta tags on a page, for example schema.org stuff, where would that go? in
the data object? Would it be called pageMeta? and how are attributes
included? Thank you!!! :)

Sincerely,

*August Bollinger*
Founder/Creator/Quant - Chayton Falke Global Equity™
Founder/Lead Data Scientist - Composite Analytics™
(949) 257-2854

Life can be absolutely phenomenal. And it should be. And it WILL be! :)

**Comment by goodbomb** [comment]
Have a look at ```app/common/common-init.js``` along with the ```app/index.html```

https://github.com/goodbomb/angular-gulp-browserify-starter/blob/develop/app/common/common-init.js

With those two files you should be able to understand how that works. You can add whatever fields you want to the data object, so you can include as many customized meta tags and attributes in there that you need. If they're static (as in they don't change between pages, then I would suggest simply hard coding those attributes inside the index.html ```<head></head>```, but if you need them to be dynamic, then you can add them to the data object in each config file.

**Comment by BollingerInternational** [comment]
Awesome. Thank you so much, Ben.

On Saturday, April 18, 2015, Ben Scott <notifications@github.com> wrote:

> Have a look at app/common/common-init.js along with the app/index.html
>
>
> https://github.com/goodbomb/angular-gulp-browserify-starter/blob/develop/app/common/common-init.js
>
> With those two files you should be able to understand how that works. You
> can add whatever fields you want to the data object, so you can include as
> many customized meta tags and attributes in there that you need. If they're
> static (as in they don't change between pages, then I would suggest simply
> hard coding those attributes inside the index.html <head></head>, but if
> you need them to be dynamic, then you can add them to the data object in
> each config file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goodbomb/angular-gulp-browserify-starter/issues/12#issuecomment-94209102>
> .
>


-- 
Sincerely,

*August Bollinger*
Founder/Creator/Quant - Chayton Falke Global Equity™
Founder/Lead Data Scientist - Composite Analytics™
(949) 257-2854

Life can be absolutely phenomenal. And it should be. And it WILL be! :)

**Comment by goodbomb** [comment]
No problem. Cheers!
