### ISSUE TITLE
Prerender.io

### ISSUE THREAD

**Issue by BollingerInternational** [goodbomb/angular-gulp-browserify-starter#16]
I am having an issue with prerender.io and the dist version. Although I have installed prerender.io code properly in the server.js file, for some reason, in the dist version of your framework I am not able to get it to work. Is there something in gulp prod that is affecting this service? Thank you.

**Comment by goodbomb** [comment]
Hi, I'm really swamped right now so I don't have time to investigate this deeply, but it's possible that Prerender.io is not compatible with browserified JS. I've never used Prerender.io, so I can't give you any specific tips on how to use it with this project. I'm afraid you'll have to figure this one out on your own (asking for help on Stackoverflow might be your best bet if google searches aren't yielding anything useful).

Sorry I can't be more help on this.

**Comment by BollingerInternational** [comment]
Ben,

Thank you. I appreciate your response. :)

Sincerely,

*August Bollinger*
Founder/Creator/Quant - Chayton Falke Global Equity™
Founder/Lead Data Scientist - Composite Analytics™
(949) 257-2854

Life can be absolutely phenomenal. And it should be. And it WILL be! :)
