### ISSUE TITLE
License

### ISSUE THREAD

**Issue by leftiness** [goodbomb/angular-gulp-browserify-starter#18]
Hello, Ben.

I saw you write a little bit ago that you're really busy. I'll keep this short.

If I build something from a fork of this project and put an MIT license on it, is that okay? Should I put a note in the readme pointing back to you? Is it even "normal" to credit the source of a structural design pattern? If not, is that why you didn't include a license file in the project? The ethics are unclear to me.

*Three days until the weekend. :)*

**Comment by goodbomb** [comment]
I agree, the ethics are indeed unclear for a structural design pattern. I'm unsure if that's something that can realistically be copyrighted to me. Technically if I don't include a license, the rights belong to me, so perhaps I should include an MIT license in this project. I'll do that first chance I get. 

For the time being, you're free to add a standard MIT license to your project referencing me (Ben Scott - bscott@tekalstudios.com) as the original creator. That should cover any potential legalities (not that I would ever take legal action against someone using this project - it is open source after all).

**Comment by goodbomb** [comment]
I've added an MIT license to both branches. You're welcome to pull that into your fork. Cheers!

**Comment by leftiness** [comment]
https://github.com/leftiness/Optical/blob/master/LICENSE

**Comment by goodbomb** [comment]
Looks good to me! Thanks for bringing this up.
