### ISSUE TITLE
adding vendore chart.js angular-chart.js

### ISSUE THREAD

**Issue by gadieichhorn** [goodbomb/angular-gulp-browserify-starter#29]
not sure if this is issue or just my lack of understanding of the setup. I am trying to add chart.js support to the vendor.js build file

> bower install angular-chart.js --save

in gulpfile I added the libs to the build

    vendorJS: {

            './libs/angular-chart.js/dist/angular-chart.js'

    vendorCSS: {

            './libs/angular-chart.js/dist/angular-chart.css', // charts JS

I am getting the following error after build
> gulp build

[16:23:19] Finished 'fonts' after 2.41 s
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'angular' from 'libs\angular-chart.js\dist'
    at node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)

I also need to add the chart.js to the angular injection process in common.js

// app/common/common.js

...
require('chart.js');
module.exports = angular.module('common',
        [
            'chart.js',
...

**Comment by goodbomb** [comment]
hey, sorry for the late response. Been a busy few days for me. Did you get this sorted out? It looks like you had it configured correctly, but I haven't had a chance to test this myself yet.

**Comment by gadieichhorn** [comment]
Thanks for getting back to me.
It is still an issue. I am not sure this is my configuration or Chart.js doesn't support browserify.
appreciate any progress on this, thanks.

**Comment by goodbomb** [comment]
Looks like the angular-chart documentation is incorrect on their homepage (http://jtblin.github.io/angular-chart.js/). Seems to be updated on the github page, though. That was really lame of them. 

'./libs/Chart.js/Chart.js' -> this is the path you need

**Comment by goodbomb** [comment]
Their homepage gives this path:
<script src="bower_components/angular-chart.js/dist/angular-chart.js"></script>

But on the github page they give this:
<script src="bower_components/angular/angular.min.js"></script>
<script src="bower_components/Chart.js/Chart.min.js"></script>
<script src="bower_components/angular-chart.js/dist/angular-chart.min.js"></script>

Looks like you need both. The angular-chart file definitely seems to have an issue.

**Comment by goodbomb** [comment]
https://github.com/jtblin/angular-chart.js/issues/220

I've opened an issue on angular-chart. Seems to be an issue on their end.

**Comment by goodbomb** [comment]
From my understanding (I haven't tried personally) you should be able to work with the node package instead of the bower component for now. As such, I'm going to close this ticket unless there's anything else.
