### ISSUE TITLE
Dublicate bundle for libs in vendorJs task

### ISSUE THREAD

**Issue by malibagci** [goodbomb/angular-gulp-browserify-starter#30]
Hi @goodbomb,

I've noticed that in gulpfile.js you added vendorJs task for bundle libs.

vendorJS: {
        // These files will be bundled into a single vendor.js file that's called at the bottom of index.html
        src: [
            './libs/angular/angular.js',
            './libs/angular-animate/angular-animate.js',
            './libs/angular-bootstrap/ui-bootstrap-tpls.js',
            './libs/angular-cookies/angular-cookies.js',
            './libs/angular-resource/angular-resource.js',
            './libs/angular-sanitize/angular-sanitize.js',
            './libs/angular-ui-router/release/angular-ui-router.js',
            './libs/jquery/dist/jquery.js',
            './libs/bootstrap/dist/js/bootstrap.js',
            './libs/domready/ready.js',
            './libs/lodash/lodash.js',
            './libs/restangular/dist/restangular.js'
        ]
    },

But this libraries added in bundle.js also with browserify. And project works without this vendorJs task.

Maybe i missed something else :)

Thanks for great project template.

**Comment by goodbomb** [comment]
Hi, sorry for the late response. Somehow missed your issue.

The key is this block of code in the gulpfile (specifically the "external" attribute):
```
bundle.conf = {
    entries: filePath.browserify.src,
    external: filePath.vendorJS.src,
    debug: true,
    cache: {},
    packageCache: {}
};
```

From the [node-browserify](https://github.com/substack/node-browserify#usage) github documentation for "b.external(file)":

```
Prevent file from being loaded into the current bundle, instead referencing from another bundle.

If file is an array, each item in file will be externalized.

If file is another bundle, that bundle's contents will be read and excluded from the current bundle as the bundle in file gets bundled.
```

**Comment by malibagci** [comment]
@goodbomb hi again :)

I understood blocks of your code but the problem is that;

When you run application with "gulp build-prod" it generates bundle.js and vendorJs.

But if you remove   "<script src="vendor.js"></script>"  tag in index.html, project still works properly.
Because, browserify  includes excluded libraries both bundleJs and VendorJs.

I think its a small configuration. If i fix this, i will add here.

Thnx

**Comment by KyleW** [comment]
What's the configuration change? I inherited a project that uses this seed and I'm trying to pull the vendor files out of bundle.js. I can't figure out what's missing.
