### ISSUE TITLE
Troubles adding ngTable to angular-gulp-browserify-starter

### ISSUE THREAD

**Issue by pablorsk** [goodbomb/angular-gulp-browserify-starter#33]
I'm trying add ngTable, but I receive this error:
```javascript
Error: [$injector:unpr] Unknown provider:
     NgTableParamsProvider <- NgTableParams <- TableCtrl
```
Or this if I dont add 'NgTableParams' to $inject array
```javascript
TypeError: NgTableParams is not a function
```

Can you help me? I follow this steps:
```bash
bower install ng-table --save
```
Next add CSS and JS to gulpfile, next gulp build. I add this to app.js
```javascript
'use strict';
var angular = require('angular');
angular.module('myApp', ['ngTable']);     // new line. It's correct here?
module.exports = angular.module('myApp',
    [
        require('./common/common.js').name,
        require('./modules').name
    ])
    .config(require('./appConfig'))
    .constant('version', require('../package.json').version)
    .run(require('./common/common-init.js'));
```
Controller:
```javascript
'use strict';
function TableCtrl($scope, NgTableParams) {
    var data = [{name: 'Moroni', age: 50} /*,*/];
    $scope.tableParams = new NgTableParams({}, { dataset: data});
}
TableCtrl.$inject = ['$scope', 'NgTableParams'];
module.exports = TableCtrl;
```
Finally add HTML like http://ng-table.com/ to view.

Regards...

**Comment by goodbomb** [comment]
There are a couple of issues with your code.

1. You're injecting "NgTableParams" into your controller, but you haven't defined it anywhere. What you defined was "NgTable". 
2. You shouldn't be defining "NgTable" in the app.js file (that file should remain largely untouched in this application structure unless you know what you're doing). You should be defining NgTable in the common.js file that you submitted your PR for, or you should be defining it directly in your controller. The common.js file is meant for dependencies that are common across your entire application. If you only need NgTable in certain views, then you should define and inject the dependency directly in your controller.

That's about as much support as I can give. I haven't used ngTable before, so I can't give you specific support on how their module works.

Hope this helps you.

Cheers!

**Comment by pablorsk** [comment]
First, ¡THANK YOU @goodbomb! 

The files *index.html* and *app.js* are like original now :)

I add library to *common.js* (assume for now ngTable is for all project).
```javascript
[...]
require('ng-table');            // obtained from ngTableLibrary/bower.json->name
require('restangular');

module.exports = angular.module('common',
    [
        'ui.bootstrap',
        'ngTable',              // obtained from ngTableLibrary/dist/ng-table.js->@name
[...]
```

Also I added more modification. I create a fork with a extra page with a new package, in this case ng-table.
https://github.com/pablorsk/angular-gulp-browserify-starter

Regards...
