### ISSUE TITLE
$stateParams undefined

### ISSUE THREAD

**Issue by JasaNiklanovic** [goodbomb/angular-gulp-browserify-starter#34]
Hey, im trying to pass params via the router and keep getting undefined for $stateParams, any ideas?

pagesRoutes.js //

```
var team = {
        name: 'pages.team',
        url: '/team/:teamId', // The ^ character makes this url override the parent url
        template: '<div about-view></div>',
        controller: 'PagesCtrl',
        data: {
            moduleClasses: 'page',
            pageClasses: 'about',
            pageTitle: 'About',
            pageDescription: 'Some description.'
        }
    };
```

**Comment by goodbomb** [comment]
What does the rest of your routes file look like?

**Comment by JasaNiklanovic** [comment]
'use strict';

function pageRoutes($stateProvider) {

    var pages = {
        name: 'pages',
        abstract: true,  // This makes it so that the url for this route doesn't actually resolve
        url: '/pages',
        template: '<div ui-view></div>', // This injects a new ui-view that the about page directive is injected into
        controller: 'PagesCtrl'
    };

    var team = {
        name: 'pages.team',
        url: '/team/:teamId', // The ^ character makes this url override the parent url
        template: '<div about-view></div>',
        controller: 'AboutCtrl',
        data: {
            moduleClasses: 'page',
            pageClasses: 'about',
            pageTitle: 'About',
            pageDescription: 'Some description.'
        }
    };

    $stateProvider.state(pages);
    $stateProvider.state(team);

}

pageRoutes.$inject = ['$stateProvider'];
module.exports = pageRoutes;

**Comment by goodbomb** [comment]
Looks correct to me. Was it working before you made any changes?

**Comment by goodbomb** [comment]
Actually, wait, :teamId looks to be the culprit.

**Comment by JasaNiklanovic** [comment]
Don't know, haven't tried; if i call the controller directly from the team object i get the stateParams; the problem is somewhere in the controller connection

**Comment by JasaNiklanovic** [comment]
so this works; var team = {
        name: 'pages.team',
        url: '/team/:teamId', // The ^ character makes this url override the parent url
        template: '<div about-view></div>',
        controller: function ($stateParams) {
            console.log($stateParams);
        }
        data: {
            moduleClasses: 'page',
            pageClasses: 'about',
            pageTitle: 'About',
            pageDescription: 'Some description.'
        }

**Comment by goodbomb** [comment]
You should make use of the code snippet for markdown so that your code is formatted correctly. 

Anyway, in your original version, you need to resolve the teamId parameter so that it can be used inside of your controller.

For example:

```
userID = {
            name: 'user.id',
            abstract: true,
            url: '/:id',
            template: '<div ui-view></div>',
            controller: 'UsersCtrl',
            resolve: {
                user: function(Restangular, $stateParams) {
                    return Restangular.one('users', $stateParams.id).get();
                }
            }
        };
```

**Comment by goodbomb** [comment]
In the above example, Restangular is making a GET request to an API that returns a specific user resource matching the supplied ID from the URL parameter :id

**Comment by goodbomb** [comment]
To be completely honest, though, there may be better ways of handling route params these days. I haven't been working with Angular for over a year now, so I'm out of touch with how things have changed. I've moved over to React now. You may want to do a bit of research of your own as well.

**Comment by JasaNiklanovic** [comment]
thanks, ill try this out and let you know
