### ISSUE TITLE
Native Services

### ISSUE THREAD

**Issue by BollingerInternational** [goodbomb/angular-gulp-browserify-starter#8]
When I inject your included service "ServiceName" into a controller, I am getting an error in the console of:

Error: [$injector:unpr] Unknown provider: ServiceNameProvider <- ServiceName <- HomeViewCtrl

I have the proper spelling, its a function attribute, and have also injected it below in the $inject area. I also see that common.js is requiring all in the services directory.

**Comment by BollingerInternational** [comment]
Disregard, I explored a little bit and found someone else with the same issue that you helped resolve. Essentially a return statement belongs in the service function, in which returns an object. Example:

var ServiceName = function() {
    return {
        excuses : [
            {id: 1, excuse: "Dog ate my homework"},
            {id: 2, excuse: "Sister ate my homework"}
        ]
    };
};
ServiceName.$inject = [];
module.exports = ServiceName;

However, I am trying to create a service with another service injected, namely the $firebase service, then I am doing a query for which I want the results to stay persistent through the app so I stay DRY. If you can talk me out of it or provide a solution before I do, I would appreciate it. Thank you.

var ServiceName = function($firebase) {
    return {
        data :  function () {
                var fb = new Firebase('https://<your firebase>.firebaseio.com'),
                     sync = $firebase(fb);
                     return sync.$asArray();
        }
    };
};
ServiceName.$inject = ['$firebase'];
module.exports = ServiceName;

**Comment by goodbomb** [comment]
Hi, glad you got your initial problem sorted out.

I've never used firebase, so I can't comment on it specifically, but what you are trying to do sounds reasonable. Stackoverflow is generally a great resource for questions that are outside the overall scope of this project. Now you're dealing with angular's dependency injection, which will work the same in any angularjs app architecture.

This question seems to deal with firebase specifically, so it may help you with your current path:
http://stackoverflow.com/questions/25344829/how-do-you-inject-dependencies-into-services-in-angular-js

**Comment by goodbomb** [comment]
Hey, did you get everything sorted out? Can I close this issue?

**Comment by BollingerInternational** [comment]
​Ben,

I didn't. I moved on to other things and will have to circle back on it.
Close it if you wish and I can get back to you later on it if that's better.

Sincerely,

*August Bollinger*
Founder/Creator/Quant - Chayton Falke Global Equity™
Founder/Lead Data Scientist - Composite Analytics™
(949) 257-2854

Life can be absolutely phenomenal. And it should be. And it WILL be! :)
